[package]
name = "smol-dfr"
version = "0.3.7"
edition = "2021"
license = "GPL-3.0"
description = "Small but mighty dynamic function row daemon"
homepage = "https://github.com/AsahiLinux/tiny-dfr"
repository = "https://github.com/AsahiLinux/tiny-dfr.git"
# Forked from tiny-dfr (https://github.com/AsahiLinux/tiny-dfr)

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
screenshot = []

[dependencies]
drm = "0.14"
anyhow = "1"
input = "0.8"
libc = "0.2"
input-linux = { version = "0.7", features = ["serde"] }
input-linux-sys = "0.9"
nix = { version = "0.29", features = ["event", "signal", "inotify"] }
privdrop = "0.5.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
rand = "0.8"
chrono = { version = "0.4", features = ["unstable-locales"] }
udev = "0.9"
niri-ipc = "=25.11.0"
iced_tiny_skia = { version = "0.13", features = ["svg"] }
iced_core = "0.13"
iced_widget = { version = "0.13", features = ["svg"] }
iced_graphics = "0.13"
iced_renderer = { version = "0.13", features = ["tiny-skia", "svg"] }
tiny-skia = "0.11"
libpulse-binding = "2.28"
